[package]
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "panic-udf"
publish = false
version = "0.0.0-alpha.0"

[dependencies]
cortex-m-udf = { path = "../cortex-m-udf" }
